server:
  port: 8088
spring:
  application:
    name: happyfire-blog
  datasource:
    url: jdbc:mysql://192.168.180.138:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:org.happyfire.blog.dao.mapper/*.xml

qiniu:
  accessKey: IUiEb93jt_k9yu0yRiGq6uYywOg42CHooPA7ArP9
  accessSecretKey: -R5D3gPRz0Vbx_J5gXgJukNeGB2Y_H8XcsRCxiEX

blog:
  path: D:\Code\IDEAProjects\blog-parent\blog-api\src\main\resources\pictures\