server:
  port: 8089
spring:
  application:
    name: happyfire-blog-admin
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:org.happyfire.blog.dao.mapper/*.xml

qiniu:
  accessKey: IUiEb93jt_k9yu0yRiGq6uYywOg42CHooPA7ArP9
  accessSecretKey: -R5D3gPRz0Vbx_J5gXgJukNeGB2Y_H8XcsRCxiEX
